services:
    node1:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=8001
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        ports:
            - "8001:8001"
        volumes:
            - ./data:/app/data
        depends_on:
            - qdrant
            - redis
        networks:
            - rag-networks

    node2:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=8002
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        ports:
            - "8002:8002"
        volumes:
            - ./data:/app/data
        depends_on:
            - qdrant
            - redis
        networks:
            - rag-networks

    node3:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=8003
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        ports:
            - "8003:8003"
        volumes:
            - ./data:/app/data
        depends_on:
            - qdrant
            - redis
        networks:
            - rag-networks

    nginx:
        image: nginx:latest
        ports:
            - "8000:8000"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - node1
            - node2
            - node3
        networks:
            - rag-networks

    qdrant:
        image: qdrant/qdrant:latest
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - qdrant_data:/qdrant/storage
        networks:
            - rag-networks

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - rag-networks

volumes:
    qdrant_data:
    redis_data:

networks:
    rag-networks:
        driver: bridge